### PR TITLE
Upgrade to Asciidoctor 1.5.5-4

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by cmoulliard** [comment]
@Mogztter Hi guillaume. Can you fix please the eslint errors reported here be https://travis-ci.org/bucharest-gold/litoria/jobs/179547785 ?

**Comment by Mogztter** [comment]
Ooops, sure I Will fix it

**Comment by cmoulliard** [comment]
@Mogztter Tests are failing using Node 4 & 6.

**Comment by Mogztter** [comment]
Tests are running fine on my box with Node 4.something .

"Test exited without ending" means that there is an exception somewhere ?
Is it possible to get the stack trace ?

Le 30 nov. 2016 9:40 AM, "Charles Moulliard" <notifications@github.com> a
écrit :

**Comment by Mogztter** [comment]
@cmoulliard Build is failing on master with the same error message: https://travis-ci.org/bucharest-gold/litoria/jobs/171422520

**Comment by cmoulliard** [comment]
I have tested your PR locally with node 4,5 or 6 and all the tests are green. I'm wondering whey that fails when executed by Travis.

**Pull request merged**
